/* import { lib } from './composition';


export class IceCream extends zim.Container {

    shape: any;
    shape_1: any;
    shape_2: any;
    instance: any;
    shape_3: any;
    shape_4: any;
    shape_5: any;
    shape_6: any;
    shape_7: any;
    shape_8: any;
    shape_9: any;
    shape_10: any;
    shape_11: any;
    shape_12: any;
    shape_13: any;
    shape_14: any;
    instance_1: any;
    shape_15: any;
    shape_16: any;
    shape_17: any;
    shape_18: any;
    shape_19: any;
    instance_2: any;
    shape_20: any;
    shape_21: any;
    shapeContainer: zim.Container;

    constructor () {
            // Ice cream
            super();
            this.createShape();
           // zog(this);

    }

    private createShape () {
        this.shape = new createjs.Shape();
        this.shape.graphics.rf(['#F2706C', '#F26E6B', '#F05A62', '#EF4D5D', '#EF495B'], [0.016, 0.043, 0.392, 0.714, 0.984], -0.7, -4.9, 0, -0.7, -4.9, 27.3).s().p('ABiB+QgCgEgFgLIgJgVIgMgOQgKgNgDgLQgDgKgHgHQgFgFgIAAQgHABgFAEQgFAFgNARIgLALQgLAKgEABQgVALgRgRQgIgIgKgNQgEgIgKACQgNACgNANQgKAMgIALQgFAIgEAMQgDAKgHAJQgFAGgHgDIgBAAQgEgHABgIQABgHAFgIQAEgGACgJIADgQIABgBQAAgGADgHQACgDACgJQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAIADgHQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIACgEQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQgEgCgEADIgGAFQgFAHgLADQgDAAgHgCQgFgFgBgIQgDgTAQgRQACgDACAAQAEgDAKgOQARgWARgOIABgBQAIgHAOgIQAdgTAkgJQAUgEAOgBIAEgBQANgFANgBIARAAQARACAOAFIADAAIAFAFQAUANAOANQAPANANAQQAPASALASQADAEACAIQAKAXAFAZQABAKgFAIQgCAEgEACQgFACgEgBQgHgBgLgHQgJgFgNgDQgEgCgEAEQgNAHgEAPQgEALAFAPQABAEAGAIQAFAJgCAKQgCAHgIABIgBAAQgFAAgEgFg');
        this.shape.setTransform(877.5 - 800, 422.7 - 400, 3.001, 3.001);

        this.shape_1 = new createjs.Shape();
        this.shape_1.graphics.f('#EF3F4D').s().p('AgVAFQACgBAEABQAIACAIgHIAJgIQAEgEAGADQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBAAIgCADQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAAAgBAAIgDACQgHAJgHABIgFABQgIAAgFgGg');
        this.shape_1.setTransform(828.5 - 800, 430.5 - 400, 3.001, 3.001);

        this.shape_2 = new createjs.Shape();
        this.shape_2.graphics.f('#EF3F4D').s().p('ABMCFQgMgEgEgMIgBgNQgDgKgGgIQgHgLgIgGQgJgIgEgOQgDgIgIgHQgEgCgFABQgEABgDADIgJANQgQAUgPAKQgRALgQgGQgQgFgHgRIgEgKQgCgFgFgGQgEgCgEABQgJAEgIAGQgUATgOAXIgCAIQgCAJgDAFQgDAHgHABQgIAAgEgFIACgBIAFAAQABAAABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAKgJADgNQADgLAKgOQAJgMAKgKQAKgJAOgBQAJgBADAHQAJANAJAJQALAJAMAAQAPgBALgLIAFgFIAHgHIAHgIIANgPQAHgHAJABQADAAADACQAIAHADAHQAFAPAFAGQAFAIAFAGQAGAHAJARIAJAVQAFAFAEAAQAHgBACgHQADgJgFgIIgCgCQgLgPAEgUQACgPASgLQADgDAGACQAOAFALAGQAGAEAHABQAKABAFgIQAEgJgCgJQgFgYgKgZQgCgHgJgMQgLgTgSgTQgQgSgRgNIgVgPQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAEABQASAHAQAJIAdATQASANAQARQAMANARAfQALATAGAQQAGATABANIABAPIAAAKIgBAHQgBAEgDADQgDACgEAAQgHABgMgDQgOgEgTgMIgegTQgEgDgJAAQgEAAgDAEIgGAIQgDADgBAGQgBAKAFAKIAIAQQAFAHgBANQgBAEgEAEQgFAEgEAAg');
        this.shape_2.setTransform(887.1 - 800, 425.8 - 400, 1.001, 1.001);

        this.instance = new lib.IcePath();
        this.instance.parent = this;
        this.instance.setTransform(883.9 - 800, 430.5 - 400, 3.001, 3.001, 0, 0, 0, 21.9, 14.2);
        this.instance.alpha = 0.199;

        this.shape_3 = new createjs.Shape();
        this.shape_3.graphics.f('#77322E').s().p('AASALQgEgLgMAAQgRAAgBAIQgDAFgEAAIACgWIAFgGIALgBQAKgCgFACIAOAGIAHAEIABAMIACAMIgBAAQgCAAgDgHg');
        this.shape_3.setTransform(843.8 - 800, 489.4 - 400, 3.001, 3.001);

        this.shape_4 = new createjs.Shape();
        this.shape_4.graphics.f('#853931').s().p('AgFAEQgBgEABgDQACgEADAAQAGAAABAFIAAACIgBADQgBAFgFAAQgEAAgBgEg');
        this.shape_4.setTransform(923.8 - 800, 506.8 - 400, 3.001, 3.001);

        this.shape_5 = new createjs.Shape();
        this.shape_5.graphics.f('#853931').s().p('AAAATIgEgCIgEgFQgCgFAAgEIgBgHQAAgFACgEQADgEADgBQAEgBAFAEQADADACAHIABAIQgBAIgDAFQgCADgDAAg');
        this.shape_5.setTransform(902.4 - 800, 492.6 - 400, 3.001, 3.001);

        this.shape_6 = new createjs.Shape();
        this.shape_6.graphics.f('#7C3530').s().p('AAJAyQgCAAgCgDIgBgHIgEgfQgDgRgCgCIgHgYIgBgJIAAgBIACgBQABgDADgBIACgBIABAAQAEABABAEQABADgCACIAAABIAAAAIADAAQAEABABAFIABAHQAAAGACAHIABAAIAAABIABAJIABAQIAAAFIAAADIgCAcIgCACIgBgBg');
        this.shape_6.setTransform(822 - 800, 485.6 - 400, 3.001, 3.001);

        this.shape_7 = new createjs.Shape();
        this.shape_7.graphics.f('#7C3530').s().p('AgIAgIgCgHIgDgNIAAgSIgBAAIAAgCIgCgJIgDgFIgBgBQgGgDADgFQACgGAGACQADABADAEIADAFIABAAIAFgBIAFADIAAAAIAKgCIACAAQAFgBACAFQACAFgFADQgCABgDAAIAAABQgEgBgCAEIgCADIAAACIAAAPQAAAJgEAKQgBAFgFAAQgEAAgCgEg');
        this.shape_7.setTransform(832.8 - 800, 483.7 - 400, 3.001, 3.001);

        this.shape_8 = new createjs.Shape();
        this.shape_8.graphics.f('#79332F').s().p('AgaAqQgGgDgDgHQgEgLAAgJIAAgfIAAABIAFAlQABAEADABIABABQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAAgEIADgjIgCgRIgBgFIAAgBQADABACAEQACgEADgBIAAAAIACAZIADAMQABACACABQACACADAAQADgBABgDIACgDQACgHAAgFIAAgUIAAgBIAFgGIACgBIABAAQAGAAACAHQACADgCAFIgBACIAAABIABAAIADAAQAEABADgBIACAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIADADIADABQgHAOgBgOQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgFACIgFAAIgCAEQAAAFgDAGQgCAFgEACQgFAEgGgBIgBAAIABAHQAAALgCAGQgBAEgFAEQgDADgFAAQgDAAgEgCg');
        this.shape_8.setTransform(833.9 - 800, 493.3 - 400, 3.001, 3.001);

        this.shape_9 = new createjs.Shape();
        this.shape_9.graphics.f('#803730').s().p('AAUAhIgEgFIgEgJIgBgHIgBgCIAAgGIgDgIIgCgFIgBgCIgEgGIAAAAIgBgCIgEgDIgDgCIgBgBIgGAAIgJACIgHAEIgDACIgBADIgCAKIgBAFIgBAKIgCAGQgDAEgEgDQgFgDgBgGIgBgIIgCgWIgDgGQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIACAAQAAAAAAAAQAAABABAAQAAAAAAgBQABAAAAAAIABAAQADgCACACIABgCIAAACQgBAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAIACgBQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABABIADACIACAAQAAABAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBIAEgBIAIgCQAIgBAFABIABAAQADgDADACIAGAFIABAAQAEgCADADIABAAQAFgFAEAEIABAAQAEgBACACIABABIAEgBQAFgDAEAEIABAAIAHgFIAFAAQAFABAAAEIgBABIgBABIgDADIgEAEIgBAAIgFAIIgFATIgCAMIgDAIIgDAEQgDADgEAAQgFAAgDgDg');
        this.shape_9.setTransform(868.1 - 800, 490 - 400, 3.001, 3.001);

        this.shape_10 = new createjs.Shape();
        this.shape_10.graphics.f('#77322E').s().p('ABgA4QgGgBgDgHQgCgGAAgGIAAgFIAAgCIAAgLIgCgIQgCgLgHgRQgBgCgDgBIgDAAIgBABIgOAeQgFAIgIAHQgEADgEABQgGAAgFgDQgIgEgFgNIgEgNIgCgFQgCgEgDgBQgEgDgFABQgDAAgEADIgGAHIgDAIIgGANIgFAJQgFAGgHADQgHADgIgEQgDgBgEgEIAAgBQgIgGgCgMIgDgJIgDgHIgGgGQgCgCgEgBIgEABIgCAEIgGAMIgGAGQgFADgGAAQgJAAgHgJQgEgHgCgIIgBgHQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAAAAAIgFgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBgEAEAAIADABIABgBQAAAAABAAQAAAAAAAAQABAAAAABQAAAAABAAIACAAIAAgBIAAgDQACgEADgCIAAABIABAHIABAPIACAMQABAEAEACQAEABADgCIABgDQACgEAAgEQABgOACgHIAAgBIABgCIAJgCQAKgCACABIAIABIAFACIABAAIAFAHIABADIAEANIAAACIAAACIADALIAFAKQADAEAFABQAGAAAEgEQACgBAAgDIAAgCQADgEAAgEIACgJIADgMIADgIIADgHIACAAIACAAIAMgBIAOgCIAPgDIAEABIAKADIAAAAQADgHAIABIACgBIAGAAIATABIACgBQAHgBAGADQADACABACIABABIADACIABAAQAEgFAFABIACgBQAFgBAEACIABAAIAHgDIAGAAIAFADIABAAQAGgDAFAAIACAAIADAAIAFADIADgJQACgGAGgBQAGAAAEAEIAAABQgEAKgBAGIgBANIgBAMIgBAZQAAANgCADQgGALgHgFQgHgEACgIIABgLIACgIIAAAAIABgCIABgFIAAgJIgBgGQgBgDgCgCIgCAAIgFAFIgFAJIgEAJIgGAVIgCAGIABAGIACAEQADAGgFAGQgDAFgFACIgDABIgJgCg');
        this.shape_10.setTransform(895.1 - 800, 495.7 - 400, 3.001, 3.001);

        this.shape_11 = new createjs.Shape();
        this.shape_11.graphics.f('#E97A42').s().p('AghAjIgGgKIABgBIADgBIABgBQABgDAAgEIAAgIIAAgBIAAgEIAAgBIAAgGIgBgCQgBAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQABgDADACIABAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBAAAAQABAAABgBQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAQACADAFgCQAFgBABgDIAAgBIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIgBgEQABgFAEACIABABQABAAAAAAQABAAAAAAQABAAAAAAQAAAAAAABIABABIAHgBQAKgBAEACIAEABIAFABIAFAAQAAAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABIAAABQACAFgGAAIgPAAIgMgCIgGAAIgCABQAAAHgEAJQgDAFgHADIgDABQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgCAIQgBAGgDAEIgCAEIgFAEIgCAAg');
        this.shape_11.setTransform(841.7 - 800, 497.8 - 400, 3.001, 3.001);

        this.shape_12 = new createjs.Shape();
        this.shape_12.graphics.f('#E97A42').s().p('ABbA0IgCAAQgGAAgEgGIgEgLIgDgQIAAgMQAAgHgCgIIgCgGIgBgDIgBgCQAAAAgBgBQAAAAgBgBQAAAAgBABQAAAAgBAAIgDAEIgHAQIgGAKIgFAGIAAAAIgIAFQgIAEgEgBQgEAAgDgDIgEgDQgFgEgCgFIgBgBIgDgKIgDgGQgCgFgEgCQgGgFgFAFIgCADIgDAEIgGAOIgGALQgFAHgDACQgIAEgDAAIgIABIgCAAQgKgDgFgHQgFgHgEgKIgFgNQgDgGgDgCIgBAAQgEACgBACIgEAGQgHAIgJAAQgFAAgFgBQgDgBgCgDQgCgDABgDQABgDADAAQADAAABADIAAABQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAGACIAFgBIAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBIAIgJIABgBIABgBIABgCIADgIQAAgBABAAQAAAAAAgBQABAAAAAAQABgBABAAQAFAAgBAFQAAAAAAAAQAAABABAAQAAAAABAAQABAAABAAQACAAACAEIACACIABABQAFADADAFIABAEQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAIAAABIAFAQIADAEIACACQAOACAAgBQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAgBIABgBIAFgIIAEgMIAAgBIABgFIADgGQABgCADgCQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAABgBQABgDAEgCQAHgEAFAAIAFgBQALgCAJAFIALAGIACABQAGACgCAHQgCAGgHgCIgEgBIgEgCIAFAJIACADQADACAAAEIABAAIAFAEIABABQAAAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAIABAAIAGgNIABgBQABgEABgBIAIgTQABgFAEgFQADgDADgBQAFgCADAEIABABIAEAAQADACABADQAAADgBAEQgBAAAAABQAAAAAAAAQAAABABAAQAAAAAAAAQAKAJAFAMIACALIABAIQAAAHgGABIAAABIAAAHIABAHIAAAAQAGAAABAGIABAAIAAAAIAAgGIAAgBQgDgDADgEIALgfIAHgPIACgEIACgCIAIgGQAEgDAEAAQAHAAADAFQACAGgBAFIgNAkIAAABIAAgDIAAgdIgBgDIgBAAIgHAKIgMAfIgBAEIAAABIAAAEIAAAJQgCAIgEAFQgDAEgFAAIgFgBg');
        this.shape_12.setTransform(896.2 - 800, 499.9 - 400, 3.001, 3.001);

        this.shape_13 = new createjs.Shape();
        this.shape_13.graphics.f('#FBAF64').s().p('AjBAFIgEgMIGLAAIgFAMIjAADg');
        this.shape_13.setTransform(882.8 - 800, 489.3 - 400, 3.001, 3.001);

        this.shape_14 = new createjs.Shape();
        this.shape_14.graphics.f('#F58444').s().p('AiRAIIgFgPIEtAAIgFAPg');
        this.shape_14.setTransform(883 - 800, 528.9 - 400, 3.001, 3.001);

        this.instance_1 = new lib.IceGroup();
        this.instance_1.parent = this;
        this.instance_1.setTransform(882.6 - 800, 549.4 - 400, 3.001, 3.001, 0, 0, 0, 16.7, 20.9);
        this.instance_1.alpha = 0.5;

        this.shape_15 = new createjs.Shape();
        this.shape_15.graphics.f('#FCBB68').s().p('AhgBCIgviDIEfAAIgkCDg');
        this.shape_15.setTransform(877.1 - 800, 506.7 - 400, 3.001, 3.001);

        this.shape_16 = new createjs.Shape();
        this.shape_16.graphics.f('#F79350').s().p('Ah6gTID1AAIgMAkQgMgFgVgGQgpgLglAAQglAAgoANIggAMg');
        this.shape_16.setTransform(882.8 - 800, 535.3 - 400, 3.001, 3.001);

        this.shape_17 = new createjs.Shape();
        this.shape_17.graphics.f('#FCBB68').s().p('AhWiSICtAAIhMElg');
        this.shape_17.setTransform(879.8 - 800, 570.2 - 400, 1.001, 1.001);

        this.shape_18 = new createjs.Shape();
        this.shape_18.graphics.f('#FAAB67').s().p('AiWBCIgviDIGLAAIguCDg');
        this.shape_18.setTransform(882.8 - 800, 506.7 - 400, 3.001, 3.001);

        this.shape_19 = new createjs.Shape();
        this.shape_19.graphics.f('#FAAB67').s().p('Ah6hkIgWAAIg1iUIGLAAIg0CUIgXAAIh6Fdg');
        this.shape_19.setTransform(882.8 - 800, 561.5 - 400, 3.001, 3.001);

        this.instance_2 = new lib.IcePath_5();
        this.instance_2.parent = this;
        this.instance_2.setTransform(882.6 - 800, 496.8 - 400, 3.001, 3.001, 0, 0, 0, 21.1, 8.1);
        this.instance_2.alpha = 0.398;

        this.shape_20 = new createjs.Shape();
        this.shape_20.graphics.rf(['#763830', '#763830'], [0, 1], 0, 0, 0, 0, 0, 22.4).s().p('AidCeQhChCAAhcQAAhcBChBQBChCBbAAQBdAABBBCQBCBCAABbQAABchCBCQhBBChdAAQhbAAhChCgAiWiWQg+A/AABXQAABYA+A/QA/A+BXAAQBYAAA/g+QA+g/AAhYQAAhXg+g/Qg/g+hYAAQhXAAg/A+g');
        this.shape_20.setTransform(882.5 - 800, 455.2 - 400, 3.001, 3.001);

        this.shape_21 = new createjs.Shape();
        this.shape_21.graphics.rf(['#984137', '#984136', '#823831', '#7A352F'], [0, 0.004, 0.259, 0.404], -4.6, -7.3, 0, -4.6, -7.3, 53).s().p('AiZCaQhAg/AAhbQAAhaBAg/QA/hABaAAQBaAABABAQBBA/gBBaQABBahBBAQhABAhaAAQhaAAg/hAg');
        this.shape_21.setTransform(882.5 - 800, 455.2 - 400, 3.001, 3.001);

        this.addChild(
            this.shape_3, this.instance, this.shape_2, this.shape_1, this.shape,
            this.shape_6, this.shape_5, this.shape_4,
            this.shape_9, this.shape_8, this.shape_7,
            this.shape_12, this.shape_11, this.shape_10,
            this.instance_1, this.shape_14, this.shape_13,
            this.shape_16, this.shape_15,
            this.shape_19, this.shape_18, this.shape_17,
            this.instance_2,
            this.shape_20,
            this.shape_21,
        );

        // this.mouseChildren = false;
        // this.setBounds(0, 0, 100, 100);
        zog(this.getBounds());
    }

}


export function IceCream2 () {

        this.super_constructor(200, 200);

        this.shape = new createjs.Shape();
        this.shape.graphics.rf(['#F2706C', '#F26E6B', '#F05A62', '#EF4D5D', '#EF495B'], [0.016, 0.043, 0.392, 0.714, 0.984], -0.7, -4.9, 0, -0.7, -4.9, 27.3).s().p('ABiB+QgCgEgFgLIgJgVIgMgOQgKgNgDgLQgDgKgHgHQgFgFgIAAQgHABgFAEQgFAFgNARIgLALQgLAKgEABQgVALgRgRQgIgIgKgNQgEgIgKACQgNACgNANQgKAMgIALQgFAIgEAMQgDAKgHAJQgFAGgHgDIgBAAQgEgHABgIQABgHAFgIQAEgGACgJIADgQIABgBQAAgGADgHQACgDACgJQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAIADgHQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIACgEQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQgEgCgEADIgGAFQgFAHgLADQgDAAgHgCQgFgFgBgIQgDgTAQgRQACgDACAAQAEgDAKgOQARgWARgOIABgBQAIgHAOgIQAdgTAkgJQAUgEAOgBIAEgBQANgFANgBIARAAQARACAOAFIADAAIAFAFQAUANAOANQAPANANAQQAPASALASQADAEACAIQAKAXAFAZQABAKgFAIQgCAEgEACQgFACgEgBQgHgBgLgHQgJgFgNgDQgEgCgEAEQgNAHgEAPQgEALAFAPQABAEAGAIQAFAJgCAKQgCAHgIABIgBAAQgFAAgEgFg');
        this.shape.setTransform(877.5, 422.7, 3.001, 3.001);

        this.shape_1 = new createjs.Shape();
        this.shape_1.graphics.f('#EF3F4D').s().p('AgVAFQACgBAEABQAIACAIgHIAJgIQAEgEAGADQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBAAIgCADQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAAAgBAAIgDACQgHAJgHABIgFABQgIAAgFgGg');
        this.shape_1.setTransform(828.5, 430.5, 3.001, 3.001);

        this.shape_2 = new createjs.Shape();
        this.shape_2.graphics.f('#EF3F4D').s().p('ABMCFQgMgEgEgMIgBgNQgDgKgGgIQgHgLgIgGQgJgIgEgOQgDgIgIgHQgEgCgFABQgEABgDADIgJANQgQAUgPAKQgRALgQgGQgQgFgHgRIgEgKQgCgFgFgGQgEgCgEABQgJAEgIAGQgUATgOAXIgCAIQgCAJgDAFQgDAHgHABQgIAAgEgFIACgBIAFAAQABAAABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAKgJADgNQADgLAKgOQAJgMAKgKQAKgJAOgBQAJgBADAHQAJANAJAJQALAJAMAAQAPgBALgLIAFgFIAHgHIAHgIIANgPQAHgHAJABQADAAADACQAIAHADAHQAFAPAFAGQAFAIAFAGQAGAHAJARIAJAVQAFAFAEAAQAHgBACgHQADgJgFgIIgCgCQgLgPAEgUQACgPASgLQADgDAGACQAOAFALAGQAGAEAHABQAKABAFgIQAEgJgCgJQgFgYgKgZQgCgHgJgMQgLgTgSgTQgQgSgRgNIgVgPQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAEABQASAHAQAJIAdATQASANAQARQAMANARAfQALATAGAQQAGATABANIABAPIAAAKIgBAHQgBAEgDADQgDACgEAAQgHABgMgDQgOgEgTgMIgegTQgEgDgJAAQgEAAgDAEIgGAIQgDADgBAGQgBAKAFAKIAIAQQAFAHgBANQgBAEgEAEQgFAEgEAAg');
        this.shape_2.setTransform(887.1, 425.8, 3.001, 3.001);

        this.instance = new lib.IcePath();
        this.instance.parent = this;
        this.instance.setTransform(883.9, 430.5, 3.001, 3.001, 0, 0, 0, 21.9, 14.2);
        this.instance.alpha = 0.199;

        this.shape_3 = new createjs.Shape();
        this.shape_3.graphics.f('#77322E').s().p('AASALQgEgLgMAAQgRAAgBAIQgDAFgEAAIACgWIAFgGIALgBQAKgCgFACIAOAGIAHAEIABAMIACAMIgBAAQgCAAgDgHg');
        this.shape_3.setTransform(843.8, 489.4, 3.001, 3.001);

        this.shape_4 = new createjs.Shape();
        this.shape_4.graphics.f('#853931').s().p('AgFAEQgBgEABgDQACgEADAAQAGAAABAFIAAACIgBADQgBAFgFAAQgEAAgBgEg');
        this.shape_4.setTransform(923.8, 506.8, 3.001, 3.001);

        this.shape_5 = new createjs.Shape();
        this.shape_5.graphics.f('#853931').s().p('AAAATIgEgCIgEgFQgCgFAAgEIgBgHQAAgFACgEQADgEADgBQAEgBAFAEQADADACAHIABAIQgBAIgDAFQgCADgDAAg');
        this.shape_5.setTransform(902.4, 492.6, 3.001, 3.001);

        this.shape_6 = new createjs.Shape();
        this.shape_6.graphics.f('#7C3530').s().p('AAJAyQgCAAgCgDIgBgHIgEgfQgDgRgCgCIgHgYIgBgJIAAgBIACgBQABgDADgBIACgBIABAAQAEABABAEQABADgCACIAAABIAAAAIADAAQAEABABAFIABAHQAAAGACAHIABAAIAAABIABAJIABAQIAAAFIAAADIgCAcIgCACIgBgBg');
        this.shape_6.setTransform(822, 485.6, 3.001, 3.001);

        this.shape_7 = new createjs.Shape();
        this.shape_7.graphics.f('#7C3530').s().p('AgIAgIgCgHIgDgNIAAgSIgBAAIAAgCIgCgJIgDgFIgBgBQgGgDADgFQACgGAGACQADABADAEIADAFIABAAIAFgBIAFADIAAAAIAKgCIACAAQAFgBACAFQACAFgFADQgCABgDAAIAAABQgEgBgCAEIgCADIAAACIAAAPQAAAJgEAKQgBAFgFAAQgEAAgCgEg');
        this.shape_7.setTransform(832.8, 483.7, 3.001, 3.001);

        this.shape_8 = new createjs.Shape();
        this.shape_8.graphics.f('#79332F').s().p('AgaAqQgGgDgDgHQgEgLAAgJIAAgfIAAABIAFAlQABAEADABIABABQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAAgEIADgjIgCgRIgBgFIAAgBQADABACAEQACgEADgBIAAAAIACAZIADAMQABACACABQACACADAAQADgBABgDIACgDQACgHAAgFIAAgUIAAgBIAFgGIACgBIABAAQAGAAACAHQACADgCAFIgBACIAAABIABAAIADAAQAEABADgBIACAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIADADIADABQgHAOgBgOQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgFACIgFAAIgCAEQAAAFgDAGQgCAFgEACQgFAEgGgBIgBAAIABAHQAAALgCAGQgBAEgFAEQgDADgFAAQgDAAgEgCg');
        this.shape_8.setTransform(833.9, 493.3, 3.001, 3.001);

        this.shape_9 = new createjs.Shape();
        this.shape_9.graphics.f('#803730').s().p('AAUAhIgEgFIgEgJIgBgHIgBgCIAAgGIgDgIIgCgFIgBgCIgEgGIAAAAIgBgCIgEgDIgDgCIgBgBIgGAAIgJACIgHAEIgDACIgBADIgCAKIgBAFIgBAKIgCAGQgDAEgEgDQgFgDgBgGIgBgIIgCgWIgDgGQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIACAAQAAAAAAAAQAAABABAAQAAAAAAgBQABAAAAAAIABAAQADgCACACIABgCIAAACQgBAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAIACgBQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABABIADACIACAAQAAABAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBIAEgBIAIgCQAIgBAFABIABAAQADgDADACIAGAFIABAAQAEgCADADIABAAQAFgFAEAEIABAAQAEgBACACIABABIAEgBQAFgDAEAEIABAAIAHgFIAFAAQAFABAAAEIgBABIgBABIgDADIgEAEIgBAAIgFAIIgFATIgCAMIgDAIIgDAEQgDADgEAAQgFAAgDgDg');
        this.shape_9.setTransform(868.1, 490, 3.001, 3.001);

        this.shape_10 = new createjs.Shape();
        this.shape_10.graphics.f('#77322E').s().p('ABgA4QgGgBgDgHQgCgGAAgGIAAgFIAAgCIAAgLIgCgIQgCgLgHgRQgBgCgDgBIgDAAIgBABIgOAeQgFAIgIAHQgEADgEABQgGAAgFgDQgIgEgFgNIgEgNIgCgFQgCgEgDgBQgEgDgFABQgDAAgEADIgGAHIgDAIIgGANIgFAJQgFAGgHADQgHADgIgEQgDgBgEgEIAAgBQgIgGgCgMIgDgJIgDgHIgGgGQgCgCgEgBIgEABIgCAEIgGAMIgGAGQgFADgGAAQgJAAgHgJQgEgHgCgIIgBgHQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAAAAAIgFgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBgEAEAAIADABIABgBQAAAAABAAQAAAAAAAAQABAAAAABQAAAAABAAIACAAIAAgBIAAgDQACgEADgCIAAABIABAHIABAPIACAMQABAEAEACQAEABADgCIABgDQACgEAAgEQABgOACgHIAAgBIABgCIAJgCQAKgCACABIAIABIAFACIABAAIAFAHIABADIAEANIAAACIAAACIADALIAFAKQADAEAFABQAGAAAEgEQACgBAAgDIAAgCQADgEAAgEIACgJIADgMIADgIIADgHIACAAIACAAIAMgBIAOgCIAPgDIAEABIAKADIAAAAQADgHAIABIACgBIAGAAIATABIACgBQAHgBAGADQADACABACIABABIADACIABAAQAEgFAFABIACgBQAFgBAEACIABAAIAHgDIAGAAIAFADIABAAQAGgDAFAAIACAAIADAAIAFADIADgJQACgGAGgBQAGAAAEAEIAAABQgEAKgBAGIgBANIgBAMIgBAZQAAANgCADQgGALgHgFQgHgEACgIIABgLIACgIIAAAAIABgCIABgFIAAgJIgBgGQgBgDgCgCIgCAAIgFAFIgFAJIgEAJIgGAVIgCAGIABAGIACAEQADAGgFAGQgDAFgFACIgDABIgJgCg');
        this.shape_10.setTransform(895.1, 495.7, 3.001, 3.001);

        this.shape_11 = new createjs.Shape();
        this.shape_11.graphics.f('#E97A42').s().p('AghAjIgGgKIABgBIADgBIABgBQABgDAAgEIAAgIIAAgBIAAgEIAAgBIAAgGIgBgCQgBAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQABgDADACIABAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBAAAAQABAAABgBQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAQACADAFgCQAFgBABgDIAAgBIAAgEQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIgBgEQABgFAEACIABABQABAAAAAAQABAAAAAAQABAAAAAAQAAAAAAABIABABIAHgBQAKgBAEACIAEABIAFABIAFAAQAAAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABIAAABQACAFgGAAIgPAAIgMgCIgGAAIgCABQAAAHgEAJQgDAFgHADIgDABQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgCAIQgBAGgDAEIgCAEIgFAEIgCAAg');
        this.shape_11.setTransform(841.7, 497.8, 3.001, 3.001);

        this.shape_12 = new createjs.Shape();
        this.shape_12.graphics.f('#E97A42').s().p('ABbA0IgCAAQgGAAgEgGIgEgLIgDgQIAAgMQAAgHgCgIIgCgGIgBgDIgBgCQAAAAgBgBQAAAAgBgBQAAAAgBABQAAAAgBAAIgDAEIgHAQIgGAKIgFAGIAAAAIgIAFQgIAEgEgBQgEAAgDgDIgEgDQgFgEgCgFIgBgBIgDgKIgDgGQgCgFgEgCQgGgFgFAFIgCADIgDAEIgGAOIgGALQgFAHgDACQgIAEgDAAIgIABIgCAAQgKgDgFgHQgFgHgEgKIgFgNQgDgGgDgCIgBAAQgEACgBACIgEAGQgHAIgJAAQgFAAgFgBQgDgBgCgDQgCgDABgDQABgDADAAQADAAABADIAAABQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAGACIAFgBIAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABgBIAIgJIABgBIABgBIABgCIADgIQAAgBABAAQAAAAAAgBQABAAAAAAQABgBABAAQAFAAgBAFQAAAAAAAAQAAABABAAQAAAAABAAQABAAABAAQACAAACAEIACACIABABQAFADADAFIABAEQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAIAAABIAFAQIADAEIACACQAOACAAgBQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAgBIABgBIAFgIIAEgMIAAgBIABgFIADgGQABgCADgCQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAABgBQABgDAEgCQAHgEAFAAIAFgBQALgCAJAFIALAGIACABQAGACgCAHQgCAGgHgCIgEgBIgEgCIAFAJIACADQADACAAAEIABAAIAFAEIABABQAAAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAIABAAIAGgNIABgBQABgEABgBIAIgTQABgFAEgFQADgDADgBQAFgCADAEIABABIAEAAQADACABADQAAADgBAEQgBAAAAABQAAAAAAAAQAAABABAAQAAAAAAAAQAKAJAFAMIACALIABAIQAAAHgGABIAAABIAAAHIABAHIAAAAQAGAAABAGIABAAIAAAAIAAgGIAAgBQgDgDADgEIALgfIAHgPIACgEIACgCIAIgGQAEgDAEAAQAHAAADAFQACAGgBAFIgNAkIAAABIAAgDIAAgdIgBgDIgBAAIgHAKIgMAfIgBAEIAAABIAAAEIAAAJQgCAIgEAFQgDAEgFAAIgFgBg');
        this.shape_12.setTransform(896.2, 499.9, 3.001, 3.001);

        this.shape_13 = new createjs.Shape();
        this.shape_13.graphics.f('#FBAF64').s().p('AjBAFIgEgMIGLAAIgFAMIjAADg');
        this.shape_13.setTransform(882.8, 489.3, 3.001, 3.001);

        this.shape_14 = new createjs.Shape();
        this.shape_14.graphics.f('#F58444').s().p('AiRAIIgFgPIEtAAIgFAPg');
        this.shape_14.setTransform(883, 528.9, 3.001, 3.001);

        this.instance_1 = new lib.IceGroup();
        this.instance_1.parent = this;
        this.instance_1.setTransform(882.6, 549.4, 3.001, 3.001, 0, 0, 0, 16.7, 20.9);
        this.instance_1.alpha = 0.5;

        this.shape_15 = new createjs.Shape();
        this.shape_15.graphics.f('#FCBB68').s().p('AhgBCIgviDIEfAAIgkCDg');
        this.shape_15.setTransform(877.1, 506.7, 3.001, 3.001);

        this.shape_16 = new createjs.Shape();
        this.shape_16.graphics.f('#F79350').s().p('Ah6gTID1AAIgMAkQgMgFgVgGQgpgLglAAQglAAgoANIggAMg');
        this.shape_16.setTransform(882.8, 535.3, 3.001, 3.001);

        this.shape_17 = new createjs.Shape();
        this.shape_17.graphics.f('#FCBB68').s().p('AhWiSICtAAIhMElg');
        this.shape_17.setTransform(879.8, 570.2, 3.001, 3.001);

        this.shape_18 = new createjs.Shape();
        this.shape_18.graphics.f('#FAAB67').s().p('AiWBCIgviDIGLAAIguCDg');
        this.shape_18.setTransform(882.8, 506.7, 3.001, 3.001);

        this.shape_19 = new createjs.Shape();
        this.shape_19.graphics.f('#FAAB67').s().p('Ah6hkIgWAAIg1iUIGLAAIg0CUIgXAAIh6Fdg');
        this.shape_19.setTransform(882.8, 561.5, 3.001, 3.001);

        this.instance_2 = new lib.IcePath_5();
        this.instance_2.parent = this;
        this.instance_2.setTransform(882.6, 496.8, 3.001, 3.001, 0, 0, 0, 21.1, 8.1);
        this.instance_2.alpha = 0.398;

        this.shape_20 = new createjs.Shape();
        this.shape_20.graphics.rf(['#763830', '#763830'], [0, 1], 0, 0, 0, 0, 0, 22.4).s().p('AidCeQhChCAAhcQAAhcBChBQBChCBbAAQBdAABBBCQBCBCAABbQAABchCBCQhBBChdAAQhbAAhChCgAiWiWQg+A/AABXQAABYA+A/QA/A+BXAAQBYAAA/g+QA+g/AAhYQAAhXg+g/Qg/g+hYAAQhXAAg/A+g');
        // this.shape_20.setTransform(882.5, 455.2, 3.001, 3.001);

        this.shape_21 = new createjs.Shape();
        this.shape_21.graphics.rf(['#984137', '#984136', '#823831', '#7A352F'], [0, 0.004, 0.259, 0.404], -4.6, -7.3, 0, -4.6, -7.3, 53).s().p('AiZCaQhAg/AAhbQAAhaBAg/QA/hABaAAQBaAABABAQBBA/gBBaQABBahBBAQhABAhaAAQhaAAg/hAg');
        // this.shape_21.setTransform(882.5, 455.2, 3.001, 3.001);



        this.addChild(
            this.shape_21,
            this.shape_20,
            this.instance_2,
            this.shape_19, this.shape_18, this.shape_17,
            this.shape_16, this.shape_15,
            this.instance_1, this.shape_14, this.shape_13,
            this.shape_12, this.shape_11, this.shape_10,
            this.shape_9, this.shape_8, this.shape_7,
            this.shape_6, this.shape_5, this.shape_4,
            this.shape_3, this.instance, this.shape_2, this.shape_1, this.shape
        );


}

extend(IceCream2, zim.Container);

 */